### ISSUE TITLE
Comparison of  full fleshed framework (AngularJS) features with individual feature libraries

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/tendrl_frontend#4]
We've previously used AngularJS as the webapp framework mainly for following purposes:
1. Routing
2. Templating
3. Data Binding
4. Lazy Loading

To go ahead with the new stack, it is essential to evaluate whether the same would continue to work for us, or choosing individual tools for those purposes (as long as they are feature rich and inter-operable).

Benefits of using individual components, in general, are:
1. **Flexibility:** - we are free to choose our own structure instead of forcing us to follow the syntax or structure defined by the framework.
2. **No lock-ins:** - we will not be impose to choose any technology just because of the fact it supported by framework.
3. **Replaceability** -  we can replace that particular library with any other in future(if that fits a better choice for our application).
4. **Modularity** - the overall structure will be more modular in the sense that it will not combine the view along with the business logic.

Cons of using individual components is that it will comes along with the learning curve.

**Comment by debloper** [comment]
Frankly speaking, the comparison here massively relies on the available engineering resources and their fluency with other tools. If the developers are fluent with one option, and the other option is a steep learning curve for them, then the advantages start to fade away and only the struggles remain.

A quick analogy will be brewed coffee vs insta-coffee. There are a lot of ways to go wrong with brewed coffee, but if you know what you're doing, you can make massively superior coffee this way than that an insta-coffee can produce. But if you're limited with the experience, taste and time, going insta-coffee may be worth it, and have less chances of screw up.

Another analogy would be game-consoles vs customized gaming PC. Where the former provides a decent gaming platform for upcoming 5-10 years, it's never ahead of the curve, and doesn't appreciate upgrade options, but the later allows keeping updated with the hardware by being modular in assembly.

**Comment by gnehapk** [comment]
AngularJS can also handle the improvement areas mentioned from the skyrings web interface and even the developers have experienced in AngularJS. Whereas going ahead with individual libraries approach, it comes with a steep learning curve. Based on the developers experience we can have a rapid development with AngularJS in a short span.

**Comment by kamleshverma1** [comment]
As we know that AngularJS 2.0 is just in released and there is no bigger community for that.
so going forward with angular 2.0 is really not safe for the time being.

We had some couple of discussion regarding front-end framework. so finally we have come-up with going ahead with ""Angular 1.5"" ( which is stable and latest version in Angular 1.x ). it has ""component"" feature. which is slightly same as Angular2.0's component . in later , any point of time upgrading from Angular 1.x to 2.0 will be easy and stable.

**Comment by nthomas-redhat** [comment]
@kamleshverma1  what are features we are going to lose out on by using 1.5? How easy to migrate from 1.5 to 2.x?

**Comment by kamleshverma1** [comment]
@nthomas-redhat  In USM-2.0 (previous one) , we have used Angular 1.5 only ... only difference is , in USM 3.0 ( new one ) we will use new features (like .. component ) of Angular 1.5 .  so hence .. there is nothing to lose in newer one .  
Only i have some concern about migration from 1.5 to 2.x . 
We are going to use **component** feature of Angular1.5  in our USM- 3.0 . so migration from 1.5 to 2.x will be easy for component wise.
But as we (front-end team) discussed , we are not going to use typescript in USM 3.0 . so might be this will create problem in migration ( Angular2.x is also support pure JS without typescript but writing code in typescript for angular 2.x is easy ).

**Comment by nthomas-redhat** [comment]
@kamleshverma1, Then its a concern for me. what is the effort involved if migration is not supported?

**Comment by gnehapk** [comment]
As mentioned earlier, AngularJS can also handle the improvement areas mentioned from the skyrings web interface and even the developers have experienced in AngularJS. Hence going ahead with AngularJS.
We are using component feature of Angular 1.5. So it will be easy to migrate to Angular 2.0 in future.
