### ISSUE TITLE
Type of web application server

### ISSUE THREAD

**Issue by debloper** [Tendrl/tendrl_frontend#7]
| Static Web App | Dynamic Web App |
| --- | --- |
| **Cheaper to develop, host, manage** | Costlier to develop, host, manage |
| Low floor, low ceiling of features | **Low floor, high ceiling of features** |
| Resistant to evolution | **Receptive to evolution** |
| Limited by Auth, CORS, Data options* | **Flexible to Auth, CORS, Data options*** |

\* Expansion on the topic of limited by Auth, CORS, Data options
- A dynamic web app will help up abstract sensitive backend URLs from the client side code, running in the browser.
- A dynamic webapp alllows implementing user login mechanisms securely, regardless of the authentication strategy.
- Gives us the flexibility of mocking the API to continue with the UI development (if API is not ready)
---

However, due to the packaging restrictions, implementing the webapp on dynamic runtime doesn't comply with the limitation in distribution/installation (can be overcome with private module registry - in future). **Which means, for the time being we have to stick with static web applications.**

This comes at a cost of the application being limited to all the feature restrictions that applies to a static web app; as well as heightened complexity of implementation of some features, which can be rather easily implemented in a dynamic app.

**Comment by gnehapk** [comment]
As mentioned above, we are going ahead with the static web app. We are using nodejs for developer dependency. This ticket may get open if the requirements change in future.
