### ISSUE TITLE
There should be a version number in api url call when called from Tendrl_frontend

### ISSUE THREAD

**Issue by fbalak** [Tendrl/tendrl_frontend#79]
As is mentioned in https://github.com/Tendrl/tendrl-api/issues/51, api query URL should be in format: `http://<hostname>/api/1.0/query` with specified version. When tendrl_frontend is installed from source then expected api calls are in format `http://<hostname>/api/query.json`. Tendrl_frontend is making calls in format `http://<hostname>/api/1.0/query` when installed from packages. Calls made by Tendrl_frontend installed from source should be corrected.

**Comment by shtripat** [comment]
@anivargi need inputs from you.

**Comment by fbalak** [comment]
It is fixed. Closing.

**Comment by fbalak** [comment]
Tested on https://github.com/Tendrl/tendrl_frontend/commit/8917d8e8006a17110f01e82ea79064b6399d652f
